#spring:
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:D:/IdeaProjects/spring-boot-hibernate/database/src/main/resources/countries;MV_STORE=false;DB_CLOSE_DELAY=-1;
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      ddl-auto: update

#spring:
#  jackson:
#    serialization:
#      wrap-root-value: true
#    deserialization:
#      unwrap-root-value: true
#  profiles:
#    active: development
#  http:
#    log-request-details: true
#server:
#  address: 127.0.0.1
#  port: 45091
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-type: PKCS12
#    key-store-password: family
#    key-alias: family
logging:
  level:
    root: info
#    org:
#      springframework:
#        security: info
#        web: info
#        websocket: info
#      apache: info
